name: "Deploy on push"
on:
    push:
        branches:
            - main

jobs:
    deploy-page:
        name: Deploy page
        uses: ./.github/workflows/deploy-page.yaml
        secrets: inherit
        with:
            environment: "prod"
